In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# Using TF like numpy

In [2]:
# Tensors and operations

In [3]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
tf.constant([[1,2,3],[4,5,6]]).shape

TensorShape([2, 3])

In [5]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
tf.constant(42).shape

TensorShape([])

In [8]:
t = tf.constant([[1,2,3],[4,5,6]])
t.shape

TensorShape([2, 3])

In [10]:
t.dtype

tf.int32

In [11]:
t[:1]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [13]:
t[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [14]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [15]:
t[...,tf.newaxis]

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [16]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [17]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [18]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [19]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

In [20]:
#numpy to tf & tf to numpy

In [21]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [22]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [23]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# changing type

In [25]:
t2 = tf.constant(34., dtype =tf.float64)
t2

<tf.Tensor: shape=(), dtype=float64, numpy=34.0>

In [26]:
tf.cast(t2, dtype = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=34.0>

In [27]:
# variables *mutuable vars

In [28]:
v = tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [29]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [30]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [31]:
v[:,2].assign([0,1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  0],
       [ 8, 10,  1]])>